---
tftp_owner: nobody
http_owner: lighttpd
BS_BOOT_KERNEL_BASE_DIRECTORY: /var/tftp
BS_CONFIG_BASE_DIRECTORY: /var/ks/configs
BS_NFS_BASE_PATH: /var/ks
BS_RELATIVE_CONFIG_DIRECTORY: configs
BS_RELATIVE_IMAGE_DIRECTORY: images
BS_RELATIVE_EXTRA_REPO_DIRECTORY: extrarepos
BS_DISTRO_CONFIGURATION_FILE: /var/ks/distros.xml
BS_HTTP_PORT_NUMBER: 80
BS_MEDIA_HOST_ADDRESS: 10.1.2.3
BS_ROLE_CONFIG_SEARCH_PATH: /opt/OPSbst/roles
